site_name: leti-R Wiki
site_url: http://letir.github.io/letir_wiki/
site_description: Documentation on everything
site_author: leti-R
theme_dir: cinder
docs_dir: docs
repo_url: https://github.com/letiR/letiR_Wiki
copyright: Copyright &copy; 2016 <a href="https://github.com/orgs/letiR">letiR team</a>
google_analytics:
# This portion has the structure of the wiki, with .md documents filed and structured here.
# There would be a way to automate all of this quite 'easily' with a bash site_description
# There is also an example on the home page with a python script that automates syncs with
# github.
extra_javascript:
    - js/Rgraphpkg.js
    - js/Rnotes.js
    - js/map_authors.js
extra_css:
    - css/perso.css
pages:
  - Home: index.md
  - R notes:
      - Useful blog posts: Rnotes.md
      - R graph packages: Rgraphpkgs.md
