site_name: leti-R Wiki
site_url:
site_description: Documentation on everything
site_author: leti-R
theme_dir: cinder
docs_dir: docs
repo_url:
copyright: Copyright &copy; 2016 <a href="https://github.com/orgs/letiR">letiR team</a>
google_analytics:

# This portion has the structure of the wiki, with .md documents filed and structured here.
# There would be a way to automate all of this quite 'easily' with a bash site_description
# There is also an example on the home page with a python script that automates syncs with
#   github.

pages:
- Home: index.md
- Test: test_page.md
